# TensorFlow Basics

In [1]:
import tensorflow as tf

In [2]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.8.0


## Tensors

In [3]:
hello = tf.constant('Hello')

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [5]:
world = tf.constant('World')

In [6]:
result = hello + world

In [7]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [8]:
type(result)

tensorflow.python.framework.ops.Tensor

In [9]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [16]:
result

b'HelloWorld'

** Computations **

In [17]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [18]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [19]:
tensor_1 + tensor_2

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [20]:
sess

In [21]:
sess.close()

## Operations

In [22]:
const = tf.constant(10)

In [23]:
fill_mat = tf.fill((4,4),10)

In [24]:
myzeros = tf.zeros((4,4))

In [25]:
myones = tf.ones((4,4))

In [26]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [27]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [28]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [29]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [30]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.3125999  -0.24306603 -0.7800353  -1.0170057 ]
 [ 0.8081948   0.07057037  0.15658504  0.314381  ]
 [ 0.11285736 -0.15637648  0.20425642 -0.16487357]
 [ 0.39591983  0.59204525  0.14492987 -0.24237972]]


[[0.10921693 0.7458793  0.10499334 0.46745896]
 [0.30457342 0.5201317  0.16357529 0.5544778 ]
 [0.40454066 0.5622755  0.30404973 0.0481987 ]
 [0.44490254 0.45191276 0.47572803 0.47078264]]




## Matrix Multiplication

In [58]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [59]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [60]:
b = tf.constant([[10],[100]])

In [61]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [62]:
result = tf.matmul(a,b)

In [63]:
result.eval()

array([[210],
       [430]])